### ISSUE TITLE
안녕하세요! NN 관련 질문입니다.

### ISSUE THREAD

**Issue by dhkstnrh** [dydtjr1128/Speaker-Recognition-using-NN#1]
안녕하세요! 

화자 인식에 대해 공부하고 있는 학생입니다.
다름이 아니라 Nerual Network 알고리즘도 종류가 ANN, CNN, DNN 등등이 있는데 단순 NN 알고리즘만 사용하신건지 궁금합니당!

**Comment by baegofa** [comment]
> 안녕하세요!
> 
> 화자 인식에 대해 공부하고 있는 학생입니다. 다름이 아니라 Nerual Network 알고리즘도 종류가 ANN, CNN, DNN 등등이 있는데 단순 NN 알고리즘만 사용하신건지 궁금합니당!
